### ISSUE TITLE
Feature request: "received funds" sound 

### ISSUE THREAD

**Issue by ghost** [nano-wallet-company/nano-wallet-android#20]
In reference to: https://www.reddit.com/r/nanocurrency/comments/8oiud9/please_devs_use_the_canoe_wallet_received_funds/

Add the sound (same sound Canoe is using):
https://notificationsounds.com/notification-sounds/definite-555

When transaction is received.

Turn sound on/off should be possible from settings. And on per default.

**Comment by zackshapiro** [comment]
Sounds are a great idea but let's find something different from what Canoe uses.

**Comment by kvrban** [comment]
My personal favorite is this sound:
https://notificationsounds.com/notification-sounds/open-ended-563

But it is up to you guys. Just add a nice "you got da Nano sound" :)

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
