### ISSUE TITLE
please also release android .apk package

### ISSUE THREAD

**Issue by huye0728** [nano-wallet-company/nano-wallet-android#25]
china users can not  access google play store.

**Comment by kvrban** [comment]
> china users can not access google play store.

Do they have access to f-droid.org ? If we would put the wallet on
f-droid.org we
get two birds with one stone.

**Comment by zackshapiro** [comment]
ok

**Comment by huye0728** [comment]
yes, f-droid.org work well. but as i talk to PlasmaPower on discord(itaobi), we have another problem: the backend light.nano.org can not access too. I suppose light.nano.org do a distrubuted deployment using Geo DNS.

**Comment by iljah** [comment]
Any developments, either apk or f-droid?

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
