### ISSUE TITLE
Bug when pasting an address

### ISSUE THREAD

**Issue by zackshapiro** [nano-wallet-company/nano-wallet-android#26]
* Whenever a user pastes an address in, we need to check that it's valid, highlight & shorten if so. 
* Don't let the user send if there's a bad address (prob put a Bool on the class, make sure that bool is true before enabling the send button
* if the user edits midway through the address, makes a bad address good, or vice versa, we should always be checking and updating the send-ability state

**Comment by PlasmaPower** [comment]
I added checksum validation in https://github.com/nano-wallet-company/nano-wallet-android/commit/a40d27dff8a07e5fab5ff4cd39bd6d9de9a6affd

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
