### ISSUE TITLE
Define project coding conventions and enforce them with static analysis tools

### ISSUE THREAD

**Issue by athkalia** [nano-wallet-company/nano-wallet-android#27]
Hello,

Would you be interested in integrating checkstyle against your project? http://checkstyle.sourceforge.net/
It's a static analysis tool for coding conventions. It can enforce a particular code style on the whole codebase. As a first step I can integrate the tool and add some rules, then as a next step I can fix all the existing issues in the codebase. Finally I can integrate this into a CI server so that on every PR if any violations are found the PR is blocked, and you would need to fix all issues to merge it in.

This is a very common practice in the industry that helps maintaining code quality in a project and keeps the PRs style consistent.

**Comment by athkalia** [comment]
@zackshapiro @PlasmaPower @szeidner Just picking random names to get a response, 

I would really appreciate it if you could provide a response on this. Are you not interested in open source contributions, or maybe not that fond of this particular idea? I could bring some of my experience with helping you guys making the project rock solid, but I cannot start on anything if I am not sure that you are happy to accept contributions. This also means having the time to review PRs and discuss on them.

Cheers,
Sakis

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
