### ISSUE TITLE
[Feature Request][UX] Detect address in clipboard when entering the send screen

### ISSUE THREAD

**Issue by SparK-Cruz** [nano-wallet-company/nano-wallet-android#33]
Copying and pasting on mobile is not pleasant, reading the clipboard and filling the form would make for a good experience. Ease of pay has a large impact in users' view and helps promoting the app.

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
