### ISSUE TITLE
[Feature Request][UX] Allow suggesting a value in receive screen

### ISSUE THREAD

**Issue by SparK-Cruz** [nano-wallet-company/nano-wallet-android#34]
Generating a QR code with a suggested value will help shopkeepers to streamline their processes.
Ease of pay for their customers and less hassle for both the store and the customer has a positive impact in marketing for the app and the currency.

**Comment by SparK-Cruz** [comment]
Duplicate of https://github.com/nano-wallet-company/nano-wallet-android/issues/3

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
