### ISSUE TITLE
[Very minor UX suggestion] Display space between every 4 characters when entering the seed?

### ISSUE THREAD

**Issue by ghost** [nano-wallet-company/nano-wallet-android#39]
It's difficult to enter a 64 characters string correctly. Imo it would be easier with an automatic space between every 4 characters. I suspect that's how many people write down their seed (I do at least and I don't think I'm alone with that).

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
