### ISSUE TITLE
Don't encourage to use Android clipboard

### ISSUE THREAD

**Issue by laurijamsa** [nano-wallet-company/nano-wallet-android#4]
According research papers and code audits performed for other crypto projects, developers are suggested to be cautions of dealing with clipboard data - especially on Android. 

[A paper about attacks on Android clipboard](http://www.cis.syr.edu/~wedu/Research/paper/clipboard_attack_dimva2014.pdf).

This issue isn't only with Nano Android wallet. Unfortunately, others are doing the same. For example, currently, [Canoe wallet](https://github.com/getcanoe/canoe) does warn about taking a screenshot but doesn't warn about risks of copying and pasting.

On the other hand, [IOTA Trinity Android wallet](https://play.google.com/store/apps/details?id=com.iota.trinity) handles this completely differently without compromising good user experience. I would suggest to try it out.

To be extra safe, same precaution should be taken on every platform. Not just on Android. Personally, I felt unsafe using even the classic old desktop wallet as the only way to store your seed was to copy and paste it.

Minimum effort I would suggest do is to make a newly generated seed look easier to write down on paper (for example whitespaces between every 3 or 4 characters) and clearly tell user that it's not suggested to use clipboard but paper and pen instead.

**Comment by rodrigoslayertech** [comment]
Already removed! Please close this!

**Comment by laurijamsa** [comment]
@slowaways Seems that copying is not possible anymore on settings page. But when creating a new wallet, user is still advised "Tap to copy".

**Comment by rodrigoslayertech** [comment]
It's true. That one should also be removed.

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
