### ISSUE TITLE
[Feature Request] Widget to scan QR-code

### ISSUE THREAD

**Issue by guilhermelawless** [nano-wallet-company/nano-wallet-android#40]
I had the idea after watching this video: https://twitter.com/esmikedoyle/status/1040746155553026051

30% of the process time is spent in opening the wallet, clicking send, then scan QR code. A widget would make this faster. Even more since there is no need to load the whole wallet, such as transaction history, immediately.

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
