### ISSUE TITLE
Mnemonics seeds

### ISSUE THREAD

**Issue by rotilho** [nano-wallet-company/nano-wallet-android#41]
Hello!

I recently released a new version of jnano-commons which provides support to Mnemonics. The current implementation supports BIP39, the same used by NanoVault.

The code is as simple as 

```java
List<String> mnemonic = NanoMnemonics.createBip39Mnemonic(SEED, NanoMnemonics.NanoMnemonicLanguage.ENGLISH)

byte[] seed = NanoMnemonics.bip39ToSeed(mnemonic, NanoMnemonics.NanoMnemonicLanguage.ENGLISH)

```
Find more here https://github.com/rotilho/jnano-commons

I hope it may help

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
