### ISSUE TITLE
Can not scan QR codes with nano_ address. Only xrb_ is working

### ISSUE THREAD

**Issue by kvrban** [nano-wallet-company/nano-wallet-android#42]
Can not scan QR codes with nano_ address. Only xrb_ is working

**Comment by Marchuck** [comment]
@kvrban  it's quite easy to workaround, you can adjust it easily. let's modify string you are receiving in `onActivityResult`:

```
String qrString = ...;//fetch from intent/bundle

if(String.valueOf(qrString).startsWith("nano_"){
    qrString =  String.valueOf(qrString).replace("nano_","xrb_");
}
```

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
