### ISSUE TITLE
Not able to receive funds

### ISSUE THREAD

**Issue by Falsen** [nano-wallet-company/nano-wallet-android#46]
I downloaded the wallet, but funds aren't received and pocketed. It just says 0, after numeros sends from another wallet. However, I entered the seed into nanovault which pocketed them and instantly the tx's showed up in the NWC wallet. So I closed nanovault and tried sending a new tx, which once again didn't get received. Opening Nanovault again fixed the issue, again.

Phone: Oneplus 6T (android 9.0.16)
App version: V.1.1 (37)

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
